# Generated by Django 4.2.3 on 2023-08-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("birthday", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ContactType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ContactData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("linkedin", "LinkedIn"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.contact")),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="groups",
            field=models.ManyToManyField(to="app.contactgroup"),
        ),
        migrations.AddField(
            model_name="contact",
            name="types",
            field=models.ManyToManyField(to="app.contacttype"),
        ),
    ]
